services:
  vllm_lab3:
    image: vllm/vllm-openai:v0.18.0
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

    environment:
      NVIDIA_VISIBLE_DEVICES: "0"
      VLLM_USE_V1: "0"

    volumes:
      - ./:/workspace
      - /mnt/ai-model:/llm

    ports:
      - "8299:8000"
    ipc: host
    # entrypoint: ["/workspace/entrypoint.sh"]

    command: >
      --model Qwen/Qwen3.5-2B
      --host 0.0.0.0
      --port 8000
      --served-model-name qwen-base
      --max-model-len 8096
      --enable-lora
      --lora-modules qwen-grpo=/workspace/lab4/grpo_output/final
      --gpu-memory-utilization 0.7
      --enforce-eager
      --trust-remote-code